02/11/2024 22:34:12 main DEBUG Main initialized
02/11/2024 22:34:29 main ERROR 
Traceback (most recent call last):
  File "main.py", line 14, in __init__
  File "main.py", line 32, in run
KeyboardInterrupt
